name: Build drupal and cypress image and push it to docker hub

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  release:
    types: [published, edited]

jobs:
  # Build and push the Docker image
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            hellosanta/docker-cypress
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2 # Info: https://github.com/docker/build-push-action/tree/releases/v2#tags
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: ./8.1/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}