name: Build drupal and cypress image and push it to docker hub

on:
  push:
    # Match all branches *without* a / in the name.
    # This will exclude "sub" branches, such as "feature branches",
    # named something like: "feature/my-feature". Those branches will
    # likely contain "work in progress" code, so we will run the tests
    # on the local machine and avoid using up GitHub Actions credits
    # (if applicable, such as in `private` repositories).
    # Filter syntax info: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    branches:
      - 'main'
  release:
    types: [published, edited]

jobs:
  # Build and push the Docker image
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Build and push image to the Docker Hub
        uses: docker/build-push-action@v2 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        # if: ${{ github.ref == 'ref/head/master' }}
        with:
          file: ./8.1/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
          tags: latest