name: Build drupal and cypress image and push it to docker hub

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  release:
    types: [published, edited]

jobs:
  # Build and push the Docker image
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            hellosanta/drupal-cypress
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}
            type=sha,
            type=raw,value=8.2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v2 # Info: https://github.com/docker/build-push-action/tree/releases/v2#tags
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: ./8.3/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Build and push 8.2
        uses: docker/build-push-action@v2 # Info: https://github.com/docker/build-push-action/tree/releases/v2#tags
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: ./8.2/Dockerfile
          tags: hellosanta/drupal-cypress:8.2
      -
        name: Build and push 8.1
        uses: docker/build-push-action@v2 # Info: https://github.com/docker/build-push-action/tree/releases/v2#tags
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: ./8.1/Dockerfile
          tags: hellosanta/drupal-cypress:8.1
      -
        name: Build and push 8.0
        uses: docker/build-push-action@v2 # Info: https://github.com/docker/build-push-action/tree/releases/v2#tags
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: ./8.0/Dockerfile
          tags: hellosanta/drupal-cypress:8.0