name: Build drupal and cypress image and push it to docker hub

on:
  release:
    types: [published, edited]

jobs:
  # Build and push the Docker image
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push image to the Docker Hub
        uses: docker/build-push-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        # if: ${{ github.ref == 'ref/head/master' }}
        with:
          context: .
          file: 8.1/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
          tags: latest